apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-test
  namespace: test-monitoring
spec:
  containers:
  - name: memory-stress
    image: progrium/stress
    args: ["--vm", "1", "--vm-bytes", "1G", "--timeout", "300s"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "2Gi"
        cpu: "500m"