[project]
name = "oncall-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.6.3",
    "anthropic>=0.54.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.0",
]
