"""Slack notification service for posting incident analyses."""

import httpx

from src.oncall_agent.config import get_config
from src.oncall_agent.utils import get_logger

logger = get_logger(__name__)
config = get_config()


class SlackNotifier:
    """Service for posting incident analysis to Slack."""

    def __init__(self):
        self.webhook_url = config.slack_webhook_url
        self.bot_token = config.slack_bot_token
        self.channel = config.slack_channel
        self.enabled = config.slack_enabled or bool(self.webhook_url)

    async def post_incident_analysis(
        self,
        incident_id: str,
        title: str,
        severity: str,
        analysis: str,
        thread_ts: str | None = None
    ) -> dict:
        """
        Post incident analysis to Slack.

        Args:
            incident_id: Unique incident identifier
            title: Incident title
            severity: Incident severity (critical, high, medium, low)
            analysis: AI-generated analysis (markdown format)
            thread_ts: Optional thread timestamp to reply to

        Returns:
            Response dict with success status and thread_ts for follow-up messages
        """
        if not self.enabled:
            logger.warning("Slack notifications disabled - no webhook URL configured")
            return {"success": False, "error": "Slack not configured"}

        # Map severity to emoji and color
        severity_map = {
            "critical": {"emoji": ":red_circle:", "color": "#FF0000"},
            "high": {"emoji": ":large_orange_circle:", "color": "#FF8C00"},
            "medium": {"emoji": ":large_yellow_circle:", "color": "#FFD700"},
            "low": {"emoji": ":large_blue_circle:", "color": "#0000FF"},
            "info": {"emoji": ":white_circle:", "color": "#808080"},
        }

        sev_info = severity_map.get(severity.lower(), severity_map["info"])

        # Truncate analysis if too long for Slack (max ~3000 chars per block)
        max_analysis_length = 2900
        if len(analysis) > max_analysis_length:
            analysis = analysis[:max_analysis_length] + "\n\n... [truncated - view full report in dashboard]"

        # Build Slack message payload
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{sev_info['emoji']} Incident Analysis: {title[:100]}",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Incident ID:*\n`{incident_id}`"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Severity:*\n{severity.upper()}"
                    }
                ]
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*AI Analysis:*\n{analysis}"
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": ":robot_face: Generated by DreamOps AI Agent"
                    }
                ]
            }
        ]

        payload = {
            "blocks": blocks,
            "attachments": [
                {
                    "color": sev_info["color"],
                    "fallback": f"Incident Analysis: {title}"
                }
            ]
        }

        # Add thread_ts for threading
        if thread_ts:
            payload["thread_ts"] = thread_ts

        try:
            async with httpx.AsyncClient() as client:
                if self.webhook_url:
                    # Use webhook URL (simpler, no bot token needed)
                    response = await client.post(
                        self.webhook_url,
                        json=payload,
                        headers={"Content-Type": "application/json"},
                        timeout=10.0
                    )

                    if response.status_code == 200:
                        logger.info(f"Posted incident analysis to Slack for {incident_id}")
                        return {"success": True, "message": "Posted to Slack"}
                    else:
                        logger.error(f"Slack webhook error: {response.status_code} - {response.text}")
                        return {"success": False, "error": f"Slack error: {response.status_code}"}

                elif self.bot_token:
                    # Use bot token (more features, can reply to threads)
                    payload["channel"] = self.channel
                    response = await client.post(
                        "https://slack.com/api/chat.postMessage",
                        json=payload,
                        headers={
                            "Content-Type": "application/json",
                            "Authorization": f"Bearer {self.bot_token}"
                        },
                        timeout=10.0
                    )

                    data = response.json()
                    if data.get("ok"):
                        logger.info(f"Posted incident analysis to Slack for {incident_id}")
                        return {
                            "success": True,
                            "thread_ts": data.get("ts"),
                            "channel": data.get("channel")
                        }
                    else:
                        logger.error(f"Slack API error: {data.get('error')}")
                        return {"success": False, "error": data.get("error")}

        except httpx.TimeoutException:
            logger.error("Timeout posting to Slack")
            return {"success": False, "error": "Timeout"}
        except Exception as e:
            logger.error(f"Error posting to Slack: {e}")
            return {"success": False, "error": str(e)}

        return {"success": False, "error": "No Slack credentials configured"}

    async def post_resolution_update(
        self,
        incident_id: str,
        title: str,
        resolution: str,
        thread_ts: str | None = None
    ) -> dict:
        """Post a resolution update to an existing Slack thread."""
        if not self.enabled:
            return {"success": False, "error": "Slack not configured"}

        blocks = [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f":white_check_mark: *Incident Resolved:* {title[:100]}"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Resolution:*\n{resolution[:2000]}"
                }
            }
        ]

        payload = {"blocks": blocks}

        if thread_ts:
            payload["thread_ts"] = thread_ts

        try:
            async with httpx.AsyncClient() as client:
                if self.webhook_url:
                    response = await client.post(
                        self.webhook_url,
                        json=payload,
                        headers={"Content-Type": "application/json"},
                        timeout=10.0
                    )
                    return {"success": response.status_code == 200}

        except Exception as e:
            logger.error(f"Error posting resolution to Slack: {e}")
            return {"success": False, "error": str(e)}

        return {"success": False, "error": "No Slack credentials configured"}


# Singleton instance
_slack_notifier: SlackNotifier | None = None


def get_slack_notifier() -> SlackNotifier:
    """Get the Slack notifier singleton."""
    global _slack_notifier
    if _slack_notifier is None:
        _slack_notifier = SlackNotifier()
    return _slack_notifier
