# App 2: Out of Memory (OOM) Kill
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app
  namespace: test-apps
  labels:
    app: memory-hog
    issue: oom-kill
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: memory-consumer
        image: polinux/stress
        command: ["stress"]
        args:
          - "--vm"
          - "1"
          - "--vm-bytes"
          - "150M"  # Trying to allocate 150MB
          - "--vm-hang"
          - "1"
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"  # But limit is only 100MB!
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: memory-hog-app
  namespace: test-apps
spec:
  selector:
    app: memory-hog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080